## KMeans Unit Tests

__ testdatasets __

- different.csv files (irisdataset...)
- sklearn randomly generated sets
- generated normal distributions with known parameters

-> cover all dimensions and sizes!


tests

- test for reproducing same solutions on same datasets
- test for normal distributions centers for all metrics, methods
- test for singletons for all metrics, methods
- test convergence, iterations, breaks and tolerance thresholds

- test for cluster centers, labeling for more complex datasets against sklearn kmeans


In [ ]:
import numpy as np
from clustering import KMeans
from sklearn.datasets import make_classification
data = make_classification(n_samples=1000,n_features=2,n_informative=2,n_classes=3,n_clusters_per_class=1,n_redundant=0)
data = data[0]

In [ ]:
clustering = KMeans(data,3)

In [ ]:
clustering.fit()

In [ ]:
centers=clustering.cluster_centers

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
plt.scatter(data[:,0],data[:,1])
plt.scatter(centers[:,0],centers[:,1],c='r',s=50)

In [ ]:
import numpy as np
from clustering import KMeans
from sklearn.datasets import make_classification
data = make_classification(n_samples=2000,n_features=2,n_informative=2,n_classes=2,n_clusters_per_class=2,n_redundant=0)
data = data[0]
clustering = KMeans(data,5)
centers=clustering.cluster_centers
import matplotlib.pyplot as plt
%matplotlib inline
plt.scatter(data[:,0],data[:,1])
plt.scatter(centers[:,0],centers[:,1],c='r',s=50)

### Singletons

In [ ]:
from numpy.random import rand

In [ ]:
singletons = rand(10,2)

In [ ]:
singleton_KMeans = KMeans(singletons,10)
cluster_centers = singleton_KMeans.cluster_centers

In [ ]:
fig,ax = plt.subplots(ncols=2,nrows=1)

ax[0].scatter(singletons[:,0],singletons[:,1])
ax[1].scatter(cluster_centers[:,0],cluster_centers[:,1],c='r')

### clustering normal distributionzzzzz

In [ ]:
from numpy.random import randn
import seaborn as sns
A = randn(10000,2)
B = A + np.ones((10000,2))*6
C = A + -np.ones((10000,2))*6

In [ ]:

plt.scatter(A[:,0],A[:,1])
plt.scatter(B[:,0],B[:,1])
plt.scatter(C[:,0],C[:,1])

In [ ]:
data = np.vstack([A,B,C]) #concatenate
kmeans = KMeans(data, 3)
kmeans.cluster_centers

### validation by scikit learn clustering

In [4]:
from sklearn.cluster import KMeans as skKmeans

In [15]:
from sklearn.datasets import make_classification
import matplotlib.pyplot as plt
from clustering import KMeans

In [39]:
data = make_classification(n_samples = 300000, n_features = 2, n_classes=4, n_clusters_per_class=1,n_informative= 2,n_redundant=0)[0]

In [40]:
data.shape

(300000, 2)

In [42]:
k=3
kmeans = KMeans(data,k)
%timeit kmeans.fit()
skmeans = skKmeans(n_clusters=k)
%timeit skmeans.fit(data)
print(skmeans.cluster_centers_)
print(kmeans.cluster_centers)

terminated by break condition.
42 iterations until termination.
terminated by break condition.
26 iterations until termination.
terminated by break condition.
39 iterations until termination.
terminated by break condition.
25 iterations until termination.
1 loop, best of 3: 925 ms per loop
1 loop, best of 3: 2.06 s per loop
[[ 1.0452951  -0.43376376]
 [-0.8312833   1.51035996]
 [-1.4988453  -1.16802874]]
[[-0.83500249  1.509505  ]
 [ 1.04324881 -0.43203485]
 [-1.50373025 -1.17231178]]


In [20]:
k=2
kmeans = KMeans(data,k)
skmeans = skKmeans(n_clusters=k)
skmeans.fit_transform(data)
print(skmeans.cluster_centers_)
print(kmeans.cluster_centers)

[[-1.39602493 -0.18656302]
 [ 0.99475099  0.13526771]]
terminated by break condition.
8 iterations until termination.
[[ 0.99475099  0.13526771]
 [-1.39602493 -0.18656302]]


In [27]:
type(kmeans.cluster_centers)

numpy.ndarray

### labeling

In [46]:
5//2.1

2.0